[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/UI/Maps/Logo.Logo
EditorStartupMap=/Game/UI/Maps/Logo.Logo
ServerDefaultMap=/Game/Maps/WaitingRoom.WaitingRoom
GlobalDefaultGameMode=/Game/UI/Blueprints/BP_NS_MainUiGameMode.BP_NS_MainUiGameMode_C
GameInstanceClass=/Game/GameFlowBP/BP_NS_GameInstance.BP_NS_GameInstance_C

[/Script/Engine.RendererSettings]
r.ReflectionMethod=1
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.Lumen.TraceMeshSDFs=0
r.Shadow.Virtual.Enable=1
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.AllowStaticLighting=False
r.SkinCache.CompileShaders=True
r.RayTracing=False
r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8
r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8
r.DefaultFeature.AutoExposure=False
r.GPUSkin.Support16BitBoneIndex=True
r.GPUSkin.UnlimitedBoneInfluences=True
SkeletalMesh.UseExperimentalChunking=1
r.Mobile.AntiAliasing=0
r.AntiAliasingMethod=4
r.Streaming.PoolSize=2000
r.Tonemapper.Sharpen=2
r.TSR.Sharpen=2
r.ScreenPercentage=100

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX11
+D3D12TargetedShaderFormats=PCD3D_SM6
+D3D11TargetedShaderFormats=PCD3D_SM5

[/Script/LinuxTargetPlatform.LinuxTargetSettings]
+TargetedRHIs=SF_VULKAN_SM6

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_ThirdPerson",NewGameName="/Script/TeamLunatic_NoSignal")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_ThirdPerson",NewGameName="/Script/TeamLunatic_NoSignal")
+ActiveClassRedirects=(OldClassName="TP_ThirdPersonGameMode",NewClassName="TeamLunatic_NoSignalGameMode")
+ActiveClassRedirects=(OldClassName="TP_ThirdPersonCharacter",NewClassName="TeamLunatic_NoSignalCharacter")
bUseLoadingScreens=false
bSmoothFrameRate=false

[/Script/Engine.GameEngine]
!NetDriverDefinitions=ClearArray
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="/Script/OnlineSubsystemSteam.SteamNetDriver",DriverClassNameFallback="/Script/OnlineSubsystemUtils.IpNetDriver")
bUseLoadingScreens=false

[/Script/OnlineSubsystemSteam.SteamNetDriver]
NetConnectionClassName="OnlineSubsystemSteam.SteamNetConnection"

[/Script/OnlineSubsystemUtils.IpNetDriver]
NetConnectionClassName="OnlineSubsystemUtils.IpConnection"
MaxClientRate=25000
MaxInternetClientRate=10000
RelevantTimeout=5.0
KeepAliveTime=0.2
InitialConnectTimeout=200.0
ConnectionTimeout=15.0
NetServerMaxTickRate=30
LanServerMaxTickRate=35
NetClientTicksPerSecond=30

[OnlineSubsystem]
DefaultPlatformService=Steam

[OnlineSubsystemSteam]
bEnabled=true
bUseSteamNetworking=true
SteamDevAppId=480
AppId=480
GameServerQueryPort=27015
GameVersion=1.0.0.0

[/Script/Engine.Player]
ConfiguredInternetSpeed=10000
ConfiguredLanSpeed=20000

[/Script/Engine.GameNetworkManager]
TotalNetBandwidth=32000
MaxDynamicBandwidth=7000
MinDynamicBandwidth=4000

[/Script/Engine.StreamingSettings]
s.AsyncLoadingThreadEnabled=True

[/Script/RenderDocPlugin.RenderDocPluginSettings]
renderdoc.AutoAttach=True

[/Script/NavigationSystem.NavigationSystemV1]
bGenerateNavigationOnlyAroundNavigationInvokers=True

[/Script/NavigationSystem.RecastNavMesh]
RuntimeGeneration=Dynamic

[/Script/AIModule.CrowdManager]
MaxAvoidedAgents=50

[/Script/Engine.CollisionProfile]
; 기존 Profiles 제거 및 수정된 Profiles 등록

[CoreRedirects]
+ClassRedirects=(OldName="/Script/TeamLunatic_NoSignal.NS_AnimNotify",NewName="/Script/TeamLunatic_NoSignal.NS_ANS_MoveStopandStartNotify")
+ClassRedirects=(OldName="/Script/TeamLunatic_NoSignal.NS_MoveStopandStartNotify",NewName="/Script/TeamLunatic_NoSignal.NS_ANS_MoveStopandStartNotify")
+ClassRedirects=(OldName="/Script/TeamLunatic_NoSignal.MyClass",NewName="/Script/TeamLunatic_NoSignal.NS_RangedWeaponAnimInstance")
+ClassRedirects=(OldName="/Script/TeamLunatic_NoSignal.NS_AnimNotify_TurnInPlaceFinished",NewName="/Script/TeamLunatic_NoSignal.NS_AN_TurnInPlaceFinished")
+ClassRedirects=(OldName="/Script/TeamLunatic_NoSignal.InventoryComponent",NewName="/Script/TeamLunatic_NoSignal.NS_InventoryComponent")

[URL]
Port=7777

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=4DD300BC41A395625631118CDC1F9185
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=
